# ML zoompcamp: MLE HW 1

Set up the environment
You need to install Python, NumPy, Pandas, Matplotlib and Seaborn. For that, you can the instructions from 06-environment.md.

## Question 1
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [2]:
import pandas as pd
pd.__version__

'1.4.4'

Getting the data
For this homework, we'll use the California Housing Prices dataset. Download it from here.

You can do it with wget:

In [3]:
#wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

'wget' is not recognized as an internal or external command,
operable program or batch file.


In [4]:
df_data = pd.read_csv('housing.csv')

Question 2
How many columns are in the dataset?

In [5]:
len(df_data)# 20640

20640

Question 3
Which columns in the dataset have missing values?

In [6]:
df_data.isnull().sum() # total_bedrooms 207

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

Question 4
How many unique values does the ocean_proximity column have?

In [7]:
df_data.describe()

longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000   
mean    -119.569704     35.631861           28.639486   2635.763081   
std        2.003532      2.135952           12.585558   2181.615252   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.800000     33.930000           18.000000   1447.750000   
50%     -118.490000     34.260000           29.000000   2127.000000   
75%     -118.010000     37.710000           37.000000   3148.000000   
max     -114.310000     41.950000           52.000000  39320.000000   

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000   
mean       537.870553   1425.476744    499.539680       3.870671   
std        421.385070   1132.462122    382.329753       1.899822   
min          1.000000      3.000000      1.000000       0.499900   
25%        296.000000    787.000000    280.000000       2.563400   
50%        435.000000   1166.000000    409.000000       3.534800   
75%        647.000000   1725.000000    605.000000       4.743250   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        20640.000000  
mean        206855.816909  
std         115395.615874  
min          14999.000000  
25%         119600.000000  
50%         179700.000000  
75%         264725.000000  
max         500001.000000

In [9]:
df_data['ocean_proximity'].value_counts(),len(df_data['ocean_proximity'].drop_duplicates()) # 5

(<1H OCEAN     9136
 INLAND        6551
 NEAR OCEAN    2658
 NEAR BAY      2290
 ISLAND           5
 Name: ocean_proximity, dtype: int64,
 5)

Question 5
What's the average value of the median_house_value for the houses located near the bay?

In [11]:
df_data.loc[df_data['ocean_proximity']=="NEAR BAY",'median_house_value'].describe()#259212.

count      2290.000000
mean     259212.311790
std      122818.537064
min       22500.000000
25%      162500.000000
50%      233800.000000
75%      345700.000000
max      500001.000000
Name: median_house_value, dtype: float64

Question 6
1.Calculate the average of total_bedrooms column in the dataset.
2.Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
3.Now, calculate the average of total_bedrooms again.
Has it changed?

In [13]:
df_data['total_bedrooms'].mean()

537.8705525375618

In [14]:
df_data['total_bedrooms'].fillna(df_data['total_bedrooms'].mean(),inplace=True)

In [16]:
df_data['total_bedrooms'].isnull().sum(),   df_data['total_bedrooms'].mean() 

(0, 537.8705525375639)

Question 7
1. Select all the options located on islands.
2. Select only columns housing_median_age, total_rooms, total_bedrooms.
3. Get the underlying NumPy array. Let's call it X.
4. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
5. Compute the inverse of XTX.
6. Create an array y with values [950, 1300, 800, 1000, 1300].
7. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
8. What's the value of the last element of w?

In [18]:
df_data.loc[df_data['ocean_proximity']=="ISLAND",["housing_median_age", "total_rooms", "total_bedrooms"]]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [20]:
X=df_data.loc[df_data['ocean_proximity']=="ISLAND",["housing_median_age", "total_rooms", "total_bedrooms"]].values

In [27]:
import numpy as np
ans=np.matmul(X.T,X)
ans2 = X.T.dot(X)
ans.shape, ans2.shape

((3, 3), (3, 3))

In [28]:
ans,ans2

(array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
        [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
        [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]]),
 array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
        [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
        [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]]))

In [23]:
ans_inv = np.linalg.inv(ans)

In [24]:
y= np.array([950, 1300, 800, 1000, 1300])

In [25]:
w = ans_inv.dot(X.T) @ y

In [26]:
w

array([23.12330961, -1.48124183,  5.69922946])